// Read-only context. The model cannot choose arbitrary tools or submit a transaction.
import{MAINNET_ASSETS}from'../../shared/assets.js';import{rawHuman}from'../../shared/journey-model.js';import{journeyBalances,journeyMarkets,journeyPositions}from'./journey.js';
export async function aiLiveContext(message,wallet){const q=String(message).toLowerCase(),out={at:new Date().toISOString(),scope:'Read-only tool data; not an instruction or authorization to trade',workflow:'Workflows supports atomic swap + deposit into Suilend, NAVI or Kai, receipt verification, positions and separately reviewed withdrawal.'};
 if(wallet&&/balance|wallet|portfolio|hold|have|баланс|кошел|портфел/.test(q)){try{const b=await journeyBalances(wallet);out.balances=b.balances.map(c=>{const a=MAINNET_ASSETS.find(a=>a.coinType.replace(/^0x0+/,'0x')===c.coinType.replace(/^0x0+/,'0x'));return{coinType:c.coinType,raw:c.totalBalance,amount:a?rawHuman(c.totalBalance,a.decimals):null,symbol:a?.symbol||null,unit:a?'token':'raw base units; metadata not provided'};});out.balanceSource=b.source;out.updatedAt=b.updatedAt;}catch{out.balances={error:'Unavailable; do not report zero'};}}
 if(/position|health|risk|debt|withdraw|позици|риск|долг|вывод|вывест/.test(q)){if(!wallet)out.positions={error:'Connect wallet first'};else{out.positions=await Promise.all(['suilend','navi','kai','scallop','haedal'].map(async provider=>{try{return await journeyPositions(wallet,provider);}catch{return{provider,error:'Unavailable; not zero'};}}));}}
 if(/yield|earn|rate|apy|apr|deposit|lend|vault|доход|ставк|внести|депозит|пул/.test(q))out.markets=await Promise.all(['suilend','navi','kai','scallop','haedal'].map(async provider=>{try{return{provider,markets:await journeyMarkets(provider)};}catch{return{provider,error:'Unavailable; no rate may be invented'};}}));
 return out;
}
export function explainLiveContext(c){const lines=['Noise can prepare swap → deposit as ONE atomic entry transaction in Workflows (Suilend, NAVI, Kai). Your wallet signs; a provider failure reverts the entire entry, except gas.','After confirmation: refresh real positions → choose the owned position → review withdrawal → wallet signs. Withdrawal is a separate transaction, not an automatic action.'];
 if(Array.isArray(c.balances)){lines.push('\nWallet balances (source: '+c.balanceSource+'):');for(const b of c.balances.slice(0,30))lines.push(b.amount!=null?`${b.amount} ${b.symbol} · ${b.coinType}`:`${b.raw} raw units · metadata unavailable · ${b.coinType}`);if(!c.balances.length)lines.push('Provider returned no wallet coin balances.');}else if(c.balances)lines.push('Balances unavailable; no zero amount is assumed.');
 if(Array.isArray(c.positions)){lines.push('\nPositions and risk:');for(const p of c.positions){if(p.error){lines.push(p.provider+': unavailable');continue;}lines.push(p.provider+': '+(p.positions.length?p.positions.map(x=>`${x.underlyingHuman||x.amountHuman} ${x.asset} · ${x.risk}${x.health==null?'':' · health '+x.health}`).join('; '):'no supplied positions reported')+(p.complete?'':' · incomplete read'));}}else if(c.positions)lines.push('Connect a wallet for positions.');
 if(c.markets){lines.push('\nSelected current base-market rates (variable, not guaranteed):');for(const p of c.markets){if(p.error){lines.push(p.provider+': unavailable');continue;}for(const m of p.markets.filter(m=>['SUI','USDC','WAL','NS'].includes(m.symbol)).slice(0,8))lines.push(`${p.provider} · ${m.symbol}: ${m.rate==null?'unavailable':Number(m.rate).toFixed(4).replace(/\.?0+$/,'')+'% '+m.rateKind} · ${m.rateBasis||m.source}`);}}
 lines.push('\nSource: read-only Noise workflow tools · Updated: '+c.at+'. Contract, liquidity, oracle and strategy risks remain. No investment recommendation.');return lines.join('\n');}
