// Ranking is non-monetary and based ONLY on receipts for digests prepared by Noise.
import{getPool}from'./pg.js';import{isWalletAddress}from'./lending.js';
let ready=null;
async function db(){if(process.env.DATABASE_URL){const p=getPool();return{query:(q,v=[])=>p.query(q,v)};}
 if(process.env.VERCEL||process.env.NODE_ENV==='production')throw new Error('Production workflow accounting requires DATABASE_URL');
 const{db}=await import('../../server/src/db.js');return{query:async(q,v=[])=>{const st=db.prepare(q.replace(/\$\d+/g,'?'));if(/^\s*SELECT/i.test(q))return{rows:st.all(...v)};st.run(...v);return{rows:[]};}};
}
async function schema(){if(!ready)ready=(async()=>{const d=await db();await d.query('CREATE TABLE IF NOT EXISTS noise_workflow_builds (digest TEXT PRIMARY KEY, wallet TEXT NOT NULL, action TEXT NOT NULL, provider TEXT NOT NULL, prepared_at TEXT NOT NULL)');await d.query('CREATE TABLE IF NOT EXISTS noise_workflow_receipts (digest TEXT PRIMARY KEY, wallet TEXT NOT NULL, action TEXT NOT NULL, provider TEXT NOT NULL, confirmed_at TEXT NOT NULL)');})().catch(e=>{ready=null;throw e;});await ready;return db();}
export async function registerJourneyBuild({expectedDigest,meta}){const d=await schema();await d.query('INSERT INTO noise_workflow_builds (digest,wallet,action,provider,prepared_at) VALUES ($1,$2,$3,$4,$5) ON CONFLICT(digest) DO NOTHING',[expectedDigest,meta.wallet,meta.action,meta.provider,new Date().toISOString()]);}
export async function recordJourneyReceipt(receipt,wallet){if(receipt.status!=='confirmed'||!Number.isFinite(Number(receipt.timestampMs))||Number(receipt.timestampMs)<=0)return false;const d=await schema(),row=(await d.query('SELECT wallet,action,provider FROM noise_workflow_builds WHERE digest=$1',[receipt.digest])).rows[0];if(!row||row.wallet.toLowerCase()!==wallet.toLowerCase())return false;await d.query('INSERT INTO noise_workflow_receipts (digest,wallet,action,provider,confirmed_at) VALUES ($1,$2,$3,$4,$5) ON CONFLICT(digest) DO NOTHING',[receipt.digest,wallet,row.action,row.provider,new Date(Number(receipt.timestampMs)).toISOString()]);return true;}
export async function journeyLeaderboard({period='all',wallet}={}){if(!['all','week','month'].includes(period))throw Object.assign(new Error('Invalid ranking period'),{code:'INVALID_PERIOD'});if(wallet&&!isWalletAddress(wallet))throw Object.assign(new Error('Invalid wallet'),{code:'INVALID_WALLET'});const d=await schema(),cutoff=new Date(period==='all'?0:Date.now()-(period==='week'?7:30)*86400000).toISOString();const rows=(await d.query("SELECT wallet,COUNT(*) AS completed,SUM(CASE WHEN action='enter' THEN 1 ELSE 0 END) AS deposits,SUM(CASE WHEN action='withdraw' THEN 1 ELSE 0 END) AS withdrawals,SUM(CASE WHEN action='swap' THEN 1 ELSE 0 END) AS swaps,MAX(confirmed_at) AS lastActivity FROM noise_workflow_receipts WHERE confirmed_at >= $1 GROUP BY wallet ORDER BY completed DESC, wallet ASC",[cutoff])).rows.map((r,i)=>({...r,completed:Number(r.completed),deposits:Number(r.deposits),withdrawals:Number(r.withdrawals),swaps:Number(r.swaps),rank:i+1}));return{items:rows.slice(0,100),viewer:wallet?rows.find(r=>r.wallet.toLowerCase()===wallet.toLowerCase())||null:null,total:rows.length,period,source:'Noise prepared digests + verified Sui success receipts; not all Sui activity',updatedAt:new Date().toISOString(),units:'Confirmed transactions (atomic swap + deposit counts once)',rewards:'No payout or financial reward is implied by rank'};}
