import{test}from'node:test';import assert from'node:assert/strict';import{mkdtempSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';import{Ed25519Keypair}from'@mysten/sui/keypairs/ed25519';
process.env.DB_PATH=join(mkdtempSync(join(tmpdir(),'noise-referral-')),'test.db');delete process.env.DATABASE_URL;delete process.env.VERCEL;delete process.env.NODE_ENV;
const{referralChallenge,referralMutate,referralStats,referralInput}=await import('../../api/_lib/referrals-live.js');const a=Ed25519Keypair.generate(),b=Ed25519Keypair.generate(),c=Ed25519Keypair.generate(),d=Ed25519Keypair.generate();const addr=k=>k.toSuiAddress();
async function proof(k,action,code){const wallet=addr(k),challenge=await referralChallenge({wallet,action,code}),sig=await k.signPersonalMessage(new TextEncoder().encode(challenge.message));return{wallet,action,code,nonce:challenge.nonce,signature:sig.signature};}
test('referral code and wallet input are strictly validated',()=>{assert.throws(()=>referralInput('bad','register','valid'));assert.throws(()=>referralInput(addr(a),'register','<bad>'));assert.throws(()=>referralInput(addr(a),'claim','valid'));assert.equal(referralInput(addr(a),'register','CODE').code,'code')});
test('referral code requires a real wallet personal-message signature',async()=>{const p=await proof(a,'register','alice');await assert.rejects(referralMutate({...p,signature:'fake'}),/INVALID_SIGNATURE/);assert.equal((await referralMutate(p)).ok,true);assert.equal((await referralStats(addr(a))).code,'alice');await assert.rejects(referralMutate(p),/INVALID_PROOF/)});
test('referral proof binds wallet, action and code',async()=>{const p=await proof(b,'register','bob');await assert.rejects(referralMutate({...p,wallet:addr(c)}),/INVALID_PROOF/);await assert.rejects(referralMutate({...p,action:'attribute'}),/INVALID_PROOF/);await assert.rejects(referralMutate({...p,code:'other'}),/INVALID_PROOF/);await referralMutate(p)});
test('referral blocks stolen codes and permanent code replacement',async()=>{await assert.rejects(referralMutate(await proof(c,'register','alice')),/CODE_TAKEN/);await assert.rejects(referralMutate(await proof(a,'register','other')),/CODE_ALREADY_REGISTERED/);await referralMutate(await proof(c,'register','carol'))});
test('referral blocks self assignment and unknown inviters',async()=>{await assert.rejects(referralMutate(await proof(a,'attribute','alice')),/SELF_REFERRAL/);await assert.rejects(referralMutate(await proof(d,'attribute','missing')),/UNKNOWN_CODE/)});
test('referral blocks duplicate and transitive circular attribution',async()=>{await referralMutate(await proof(b,'attribute','alice'));await referralMutate(await proof(c,'attribute','bob'));await assert.rejects(referralMutate(await proof(a,'attribute','carol')),/CIRCULAR_REFERRAL/);await assert.rejects(referralMutate(await proof(b,'attribute','carol')),/ALREADY_ATTRIBUTED/)});
test('expired referral challenge cannot be used',async()=>{const p=await proof(d,'register','dave');const{db}=await import('../src/db.js');db.prepare('UPDATE noise_ref_challenges SET expires_at=? WHERE nonce=?').run('2000-01-01T00:00:00.000Z',p.nonce);await assert.rejects(referralMutate(p),/INVALID_PROOF/)});
test('referral counts only verified workflow receipts after attribution, not old activity or earnings',async()=>{const{db}=await import('../src/db.js');let s=await referralStats(addr(a));assert.equal(s.referred,1);assert.equal(s.active,0);db.prepare('INSERT INTO noise_workflow_receipts VALUES (?,?,?,?,?)').run('older',addr(b),'enter','suilend','2000-01-01T00:00:00.000Z');db.prepare('INSERT INTO noise_workflow_receipts VALUES (?,?,?,?,?)').run('verified',addr(b),'enter','suilend',new Date(Date.now()+1000).toISOString());s=await referralStats(addr(a));assert.equal(s.completed,1);assert.equal(s.active,1);assert.match(s.payouts,/Not configured/);assert.equal(s.earned,undefined)});
