// Exact, dependency-free workflow state and amount rules, shared by API and UI.
export const JOURNEY_PROVIDERS=['suilend','navi','kai','scallop','haedal','springsui','metastable','volo'];
export function fail(code,message){throw Object.assign(new Error(message||code),{code});}
export function rawHuman(raw,decimals){const n=BigInt(raw),scale=10n**BigInt(decimals);return String(n/scale)+(n%scale?'.'+String(n%scale).padStart(decimals,'0').replace(/0+$/,''):'');}
export function humanRaw(value,decimals){if(!Number.isInteger(decimals)||decimals<0||decimals>18||!/^\d+(\.\d+)?$/.test(String(value)))fail('INVALID_AMOUNT');const[a,b='']=String(value).split('.');if(b.length>decimals)fail('INVALID_AMOUNT','Too many decimal places');return String(BigInt(a)*10n**BigInt(decimals)+BigInt(b.padEnd(decimals,'0')||'0'));}
export function scaledNaviRaw(value,decimals){const s=String(value);if(!/^\d+(\.\d+)?$/.test(s))fail('POSITION_UNAVAILABLE');const[a,b='']=s.split('.');return String((BigInt(a+b)*10n**BigInt(decimals))/(10n**BigInt(9+b.length)));}
export function validateJourney(b){if(!b||!['enter','withdraw','swap','claim'].includes(b.action))fail('INVALID_ACTION');if(b.action==='claim'&&b.provider!=='haedal')fail('INVALID_PROVIDER');if(!/^0x[\da-fA-F]{64}$/.test(b.wallet||''))fail('INVALID_WALLET');if(b.action!=='swap'&&!JOURNEY_PROVIDERS.includes(b.provider))fail('INVALID_PROVIDER');if(!/^\d+$/.test(String(b.amountMist))||BigInt(b.amountMist)<=0n||BigInt(b.amountMist)>18446744073709551615n)fail('INVALID_AMOUNT');const slip=Number(b.slippageBps??50);if(!Number.isInteger(slip)||slip<1||slip>300)fail('INVALID_SLIPPAGE','Use 1–300 bps slippage');return{...b,amountMist:String(b.amountMist),slippageBps:slip};}
export function checkReceipt(tx,wallet,expectedDigest){if(!tx||tx.digest!==expectedDigest)fail('RECEIPT_MISMATCH','Digest does not match the reviewed transaction');if(tx.transaction?.data?.sender?.toLowerCase()!==wallet.toLowerCase())fail('RECEIPT_MISMATCH','Transaction sender does not match connected wallet');const status=tx.effects?.status?.status;if(!['success','failure'].includes(status))fail('RECEIPT_UNAVAILABLE');return{status:status==='success'?'confirmed':'failed',digest:tx.digest,error:tx.effects?.status?.error||null,balanceChanges:(tx.balanceChanges||[]).filter(c=>(c.address||c.owner?.AddressOwner||'').toLowerCase()===wallet.toLowerCase()).map(c=>({coinType:c.coinType,amount:String(c.amount)})),checkpoint:tx.checkpoint??null,timestampMs:tx.timestampMs??null};}
export function canRebuild(job){return !job||['confirmed','failed','rejected','not-submitted'].includes(job.status);}
export function riskLabel(debt,health){if(debt===null)return'Risk unavailable';if(!debt)return'No current borrowing · protocol risk remains';if(health==null||!Number.isFinite(health))return'Debt present · health unavailable';return health<=1?'Liquidation threshold reached':health<1.3?'Low health buffer':'Debt present · monitor liquidation health';}
